### PR TITLE
#53 #48 fix: use stage auth for dev and stage remove scope dep

### PR DESCRIPTION
**Pull request by snaveevans**

### CODE REVIEW

**Comment by snaveevans** [comment]
Note this change requires the `FirebaseJson` environment variable or `dotnet user-secrets` to be updated to use the new stage project.

**Comment by jantaylor** [comment]
Do we need to download a new firebase.json?

**Comment by snaveevans** [comment]
@jantaylor  Yes you will need to download a new firebase.json file.  I'll add you and @HeedfulCrayon to the new firebase project.

**Comment by snaveevans** [comment]
@jantaylor Are you sure your database is up and running?  That looks like it wasn't able to connect.  Secondly did you get the new firebase json entered into your `dotnet user-secrets`?

**Comment by jantaylor** [comment]
> Are you sure your database is up and running? That looks like it wasn't able to connect. Secondly did you get the new firebase json entered into your `dotnet user-secrets`?

@snaveevans Yes, the database is up and it works on `develop`, but not on this branch. Let me remove the account from the database. I wonder if the id changed and it's matching up but it's invalid.

**Pull request merged**
